### ISSUE TITLE
FAQ page on Readme points to a 403

### ISSUE THREAD

**Issue by Willianvdv** [Hacker0x01/hacker101#1]
I can't access https://www.hackerone.com/hacker101

**Comment by lahuke** [comment]
It doesn’t go live until 11am PT 1/25

- Luke -

On Jan 24, 2018, at 3:49 AM, Willian van der Velde <notifications@github.com>
wrote:

I can't access https://www.hackerone.com/hacker101

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/Hacker0x01/hacker101/issues/1>, or mute the thread

**Comment by reedloden** [comment]
It's live!
