### ISSUE TITLE
NO solutions to course work

### ISSUE THREAD

**Issue by ehpankaj** [Hacker0x01/hacker101#38]
There is no solutions to course work.

**Comment by Matt-Lepley** [comment]
I agree with this. Since this CTF isn't super popular there aren't write ups or explanations anywhere showing solutions as some other CTFs have. Is there a possibility to just add a `solutions` dir to the repo? 

I feel like I'm really close to getting a few flags but have been spinning for days now. There is a point where it isn't beneficial to just keep running into the same walls without any guidance on if you are going the right way.

**Comment by fabianjs** [comment]
Same here... I'd be happy to join anyone/any group going through the challenges... Currently stuck having 18 of the 30 flags.
Of course, I'd also share what I got so far.
